/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module labtimer (
  input CLK,
  input SW,
  input B3,
  input B2,
  input B1,
  input B0,
  input HZ1,
  output [3:0] M10,
  output [3:0] M1,
  output [3:0] S10,
  output [3:0] S1
);
  wire [3:0] M10_temp;
  wire [3:0] M1_temp;
  wire [3:0] S10_temp;
  wire [3:0] S1_temp;
  wire s0;
  wire s2;
  wire s3;
  wire s4;
  wire [3:0] s5;
  wire s6;
  wire [3:0] s7;
  wire s8;
  wire [3:0] s9;
  wire s11;
  wire [3:0] s12;
  wire s13;
  wire [3:0] s14;
  wire [3:0] s15;
  wire [3:0] s16;
  wire [3:0] s17;
  wire [3:0] s18;
  wire [3:0] s19;
  wire [3:0] s20;
  wire [3:0] s21;
  wire [3:0] s22;
  wire s23;
  wire [3:0] s24;
  wire s25;
  wire [3:0] s26;
  wire s27;
  wire [3:0] s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire [3:0] s39;
  wire [3:0] s40;
  wire s41;
  wire s42;
  wire [3:0] s43;
  wire [3:0] s44;
  wire [3:0] s45;
  wire [3:0] s46;
  wire s47;
  wire s48;
  wire [3:0] s49;
  wire [3:0] s50;
  wire s51;
  wire s52;
  wire [3:0] s53;
  wire [3:0] s54;
  wire s55;
  wire s56;
  wire [3:0] s57;
  wire [3:0] s58;
  wire s59;
  wire s60;
  wire [3:0] s61;
  wire [3:0] s62;
  wire s63;
  wire s64;
  wire [3:0] s65;
  wire [3:0] s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( B3 ),
    .C( CLK ),
    .Q( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( B2 ),
    .C( CLK ),
    .Q( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( B1 ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( B0 ),
    .C( CLK ),
    .Q( s4 )
  );
  assign s37 = ~ SW;
  assign s30 = ~ SW;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( HZ1 ),
    .C( CLK ),
    .Q( s71 )
  );
  assign s31 = (~ s71 & HZ1);
  assign s6 = (((~ s4 & B0) & SW) | (s30 & s31));
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i5 (
    .D( s5 ),
    .C( CLK ),
    .en( s6 ),
    .Q( S1_temp )
  );
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i6 (
    .D( s7 ),
    .C( CLK ),
    .en( s8 ),
    .Q( S10_temp )
  );
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i7 (
    .D( s9 ),
    .C( CLK ),
    .en( s11 ),
    .Q( M1_temp )
  );
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i8 (
    .D( s12 ),
    .C( CLK ),
    .en( s13 ),
    .Q( M10_temp )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i9 (
    .sel( SW ),
    .in_0( s14 ),
    .in_1( s15 ),
    .out( s12 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i10 (
    .sel( SW ),
    .in_0( s16 ),
    .in_1( s17 ),
    .out( s9 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i11 (
    .sel( SW ),
    .in_0( s18 ),
    .in_1( s19 ),
    .out( s7 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i12 (
    .sel( SW ),
    .in_0( s20 ),
    .in_1( s21 ),
    .out( s5 )
  );
  assign s8 = (((~ s3 & B1) & SW) | (~ s68 & s52));
  assign s11 = (((~ s2 & B2) & SW) | (~ s69 & s60));
  assign s13 = ((SW & (~ s0 & B3)) | (~ s70 & s67));
  assign s38 = (((s35 & s34 & s32 & s33) & ~ s36) | (s36 & s37));
  // count_dir
  DIG_Register DIG_Register_i13 (
    .D( s38 ),
    .C( CLK ),
    .en( s37 ),
    .Q( s36 )
  );
  assign s51 = ((s41 & s31 & s36) | (s42 & s31 & ~ s36));
  assign s52 = (s30 & s51);
  assign s59 = ((s47 & s31 & s36) | (s48 & s31 & ~ s36));
  assign s60 = (s30 & s51 & s59);
  assign s67 = (s30 & s51 & ((s55 & s36 & s36) | (s56 & s31 & ~ s36)) & s59);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i14 (
    .D( s52 ),
    .C( CLK ),
    .Q( s68 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( s60 ),
    .C( CLK ),
    .Q( s69 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i16 (
    .D( s67 ),
    .C( CLK ),
    .Q( s70 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i17 (
    .a( M10_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s22 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i18 (
    .a( M10_temp ),
    .b( 4'b1001 ),
    .\= ( s23 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i19 (
    .a( M1_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s24 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i20 (
    .a( M1_temp ),
    .b( 4'b1001 ),
    .\= ( s25 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i21 (
    .a( S10_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s26 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i22 (
    .a( S10_temp ),
    .b( 4'b101 ),
    .\= ( s27 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i23 (
    .a( S1_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s28 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i24 (
    .a( S1_temp ),
    .b( 4'b1001 ),
    .\= ( s29 )
  );
  // Zero_Detect
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i25 (
    .a( S10_temp ),
    .b( 4'b0 ),
    .\= ( s32 )
  );
  // Zero_Detect
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i26 (
    .a( S1_temp ),
    .b( 4'b0 ),
    .\= ( s33 )
  );
  // Zero_Detect
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i27 (
    .a( M1_temp ),
    .b( 4'b0 ),
    .\= ( s34 )
  );
  // Zero_Detect
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i28 (
    .a( M10_temp ),
    .b( 4'b0 ),
    .\= ( s35 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i29 (
    .a( S1_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s39 )
  );
  DIG_Sub #(
    .Bits(4)
  )
  DIG_Sub_i30 (
    .a( S1_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s40 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i31 (
    .a( S1_temp ),
    .b( 4'b1001 ),
    .\= ( s41 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i32 (
    .a( S1_temp ),
    .b( 4'b0 ),
    .\= ( s42 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i33 (
    .a( S10_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s45 )
  );
  DIG_Sub #(
    .Bits(4)
  )
  DIG_Sub_i34 (
    .a( S10_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s46 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i35 (
    .a( S10_temp ),
    .b( 4'b101 ),
    .\= ( s47 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i36 (
    .a( S10_temp ),
    .b( 4'b0 ),
    .\= ( s48 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i37 (
    .a( M1_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s53 )
  );
  DIG_Sub #(
    .Bits(4)
  )
  DIG_Sub_i38 (
    .a( M1_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s54 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i39 (
    .a( M1_temp ),
    .b( 4'b1001 ),
    .\= ( s55 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i40 (
    .a( M1_temp ),
    .b( 4'b0 ),
    .\= ( s56 )
  );
  DIG_Add #(
    .Bits(4)
  )
  DIG_Add_i41 (
    .a( M10_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s61 )
  );
  DIG_Sub #(
    .Bits(4)
  )
  DIG_Sub_i42 (
    .a( M10_temp ),
    .b( 4'b1 ),
    .c_i( 1'b0 ),
    .s( s62 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i43 (
    .a( M10_temp ),
    .b( 4'b1001 ),
    .\= ( s63 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i44 (
    .a( M10_temp ),
    .b( 4'b0 ),
    .\= ( s64 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i45 (
    .sel( s23 ),
    .in_0( s22 ),
    .in_1( 4'b0 ),
    .out( s15 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i46 (
    .sel( s25 ),
    .in_0( s24 ),
    .in_1( 4'b0 ),
    .out( s17 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i47 (
    .sel( s27 ),
    .in_0( s26 ),
    .in_1( 4'b0 ),
    .out( s19 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i48 (
    .sel( s29 ),
    .in_0( s28 ),
    .in_1( 4'b0 ),
    .out( s21 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i49 (
    .sel( s41 ),
    .in_0( s39 ),
    .in_1( 4'b0 ),
    .out( s43 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i50 (
    .sel( s42 ),
    .in_0( s40 ),
    .in_1( 4'b1001 ),
    .out( s44 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i51 (
    .sel( s47 ),
    .in_0( s45 ),
    .in_1( 4'b0 ),
    .out( s49 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i52 (
    .sel( s48 ),
    .in_0( s46 ),
    .in_1( 4'b101 ),
    .out( s50 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i53 (
    .sel( s55 ),
    .in_0( s53 ),
    .in_1( 4'b0 ),
    .out( s57 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i54 (
    .sel( s56 ),
    .in_0( s54 ),
    .in_1( 4'b1001 ),
    .out( s58 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i55 (
    .sel( s63 ),
    .in_0( s61 ),
    .in_1( 4'b0 ),
    .out( s65 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i56 (
    .sel( s64 ),
    .in_0( s62 ),
    .in_1( 4'b1001 ),
    .out( s66 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i57 (
    .sel( s36 ),
    .in_0( s44 ),
    .in_1( s43 ),
    .out( s20 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i58 (
    .sel( s36 ),
    .in_0( s50 ),
    .in_1( s49 ),
    .out( s18 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i59 (
    .sel( s36 ),
    .in_0( s58 ),
    .in_1( s57 ),
    .out( s16 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i60 (
    .sel( s36 ),
    .in_0( s66 ),
    .in_1( s65 ),
    .out( s14 )
  );
  assign M10 = M10_temp;
  assign M1 = M1_temp;
  assign S10 = S10_temp;
  assign S1 = S1_temp;
endmodule
